(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADCTODISTANCE"
   "<ADCTODISTANCE-REQUEST>"
   "ADCTODISTANCE-REQUEST"
   "<ADCTODISTANCE-RESPONSE>"
   "ADCTODISTANCE-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "ANALOGTODISTANCE"
   "<ANALOGTODISTANCE-REQUEST>"
   "ANALOGTODISTANCE-REQUEST"
   "<ANALOGTODISTANCE-RESPONSE>"
   "ANALOGTODISTANCE-RESPONSE"
  ))

