// Generated by gencpp from file beginner_tutorials/AdcToDistanceResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADCTODISTANCERESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_ADCTODISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct AdcToDistanceResponse_
{
  typedef AdcToDistanceResponse_<ContainerAllocator> Type;

  AdcToDistanceResponse_()
    : inches(0.0)
    , cm(0.0)  {
    }
  AdcToDistanceResponse_(const ContainerAllocator& _alloc)
    : inches(0.0)
    , cm(0.0)  {
  (void)_alloc;
    }



   typedef float _inches_type;
  _inches_type inches;

   typedef float _cm_type;
  _cm_type cm;





  typedef boost::shared_ptr< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AdcToDistanceResponse_

typedef ::beginner_tutorials::AdcToDistanceResponse_<std::allocator<void> > AdcToDistanceResponse;

typedef boost::shared_ptr< ::beginner_tutorials::AdcToDistanceResponse > AdcToDistanceResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::AdcToDistanceResponse const> AdcToDistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/sytasch/ROS/turtle/catkin_ws/src/intro_to_ros/sample_code/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b156c80b7b5144adc6d5f0583ac291f";
  }

  static const char* value(const ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b156c80b7b5144aULL;
  static const uint64_t static_value2 = 0xdc6d5f0583ac291fULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/AdcToDistanceResponse";
  }

  static const char* value(const ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 inches\n\
float32 cm\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inches);
      stream.next(m.cm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdcToDistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::AdcToDistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "inches: ";
    Printer<float>::stream(s, indent + "  ", v.inches);
    s << indent << "cm: ";
    Printer<float>::stream(s, indent + "  ", v.cm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADCTODISTANCERESPONSE_H
