// Generated by gencpp from file beginner_tutorials/distance.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_DISTANCE_H
#define BEGINNER_TUTORIALS_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct distance_
{
  typedef distance_<ContainerAllocator> Type;

  distance_()
    : raw(0)
    , inch(0.0)
    , cm(0.0)  {
    }
  distance_(const ContainerAllocator& _alloc)
    : raw(0)
    , inch(0.0)
    , cm(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _raw_type;
  _raw_type raw;

   typedef float _inch_type;
  _inch_type inch;

   typedef float _cm_type;
  _cm_type cm;





  typedef boost::shared_ptr< ::beginner_tutorials::distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::distance_<ContainerAllocator> const> ConstPtr;

}; // struct distance_

typedef ::beginner_tutorials::distance_<std::allocator<void> > distance;

typedef boost::shared_ptr< ::beginner_tutorials::distance > distancePtr;
typedef boost::shared_ptr< ::beginner_tutorials::distance const> distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/sytasch/ROS/turtle/catkin_ws/src/intro_to_ros/sample_code/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5266ff5b846e219dfd622ac9a1b131ed";
  }

  static const char* value(const ::beginner_tutorials::distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5266ff5b846e219dULL;
  static const uint64_t static_value2 = 0xfd622ac9a1b131edULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/distance";
  }

  static const char* value(const ::beginner_tutorials::distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 raw\n\
float32 inch\n\
float32 cm\n\
";
  }

  static const char* value(const ::beginner_tutorials::distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.raw);
      stream.next(m.inch);
      stream.next(m.cm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::distance_<ContainerAllocator>& v)
  {
    s << indent << "raw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.raw);
    s << indent << "inch: ";
    Printer<float>::stream(s, indent + "  ", v.inch);
    s << indent << "cm: ";
    Printer<float>::stream(s, indent + "  ", v.cm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DISTANCE_H
